// CollabNet Subversion Edge
// Copyright (C) 2011, CollabNet Inc. All rights reserved.
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

alter table SERVER add column DUMP_DIR VARCHAR(255) default '' NOT NULL;
alter table SERVER add column USE_HTTPV2 boolean default true NOT NULL;

CREATE MEMORY TABLE CLOUD_SERVICES_CONFIGURATION (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  VERSION BIGINT NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  DOMAIN VARCHAR(255) NOT NULL
);

alter table REPOSITORY add column CLOUD_NAME varchar(255);
alter table REPOSITORY add column CLOUD_SVN_URI varchar(255);
