/*
 * CollabNet Subversion Edge
 * Copyright (C) 2011, CollabNet Inc. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *  
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.collabnet.svnedge.schema;

import org.apache.log4j.Logger;

import java.sql.SQLException;

public class MS007AddEmailConfig implements MigrationScript {
    private Logger log = Logger.getLogger(getClass());

    public boolean migrate(SqlUtil db) throws SQLException {
        
        int[] version = {2,3,0};
        if (!db.isSchemaCurrent(version)) {
            String createTable = "CREATE MEMORY TABLE MAIL_CONFIGURATION(" +
                    "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) " +
                    "  NOT NULL PRIMARY KEY, " +
                    "VERSION BIGINT NOT NULL, " +
                    "SERVER_NAME VARCHAR(255) NOT NULL, " +
                    "PORT INTEGER NOT NULL, " +
                    // AUTH_METHOD not being used, but not removing it yet.
                    "AUTH_METHOD VARCHAR(16), " +
                    "AUTH_PASSWORD VARCHAR(255), " +
                    "AUTH_USERNAME VARCHAR(255), " +
                    "SECURITY_METHOD VARCHAR(16) NOT NULL, " +
                    "ENABLED BOOLEAN NOT NULL, " +
                    "CONSTRAINT MAIL_SERVER_NAME UNIQUE(SERVER_NAME))";        
            db.executeUpdateSql(createTable);
        }
        
        int[] version1 = {2,3,1};
        if (!db.isSchemaCurrent(version1)) {
            db.executeUpdateSql("alter table MAIL_CONFIGURATION " +
            "add column FROM_ADDRESS VARCHAR(255)");
            db.executeUpdateSql("alter table MAIL_CONFIGURATION " +
            "alter column AUTH_USERNAME rename to AUTH_USER");
            db.executeUpdateSql("alter table MAIL_CONFIGURATION " +
            "alter column AUTH_PASSWORD rename to AUTH_PASS");
        }
        
        return false;
    }
    
    public int[] getVersion() {
        return new int[] {2,3,1};
    }
}
