/*
 * CollabNet Subversion Edge
 * Copyright (C) 2011, CollabNet Inc. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *  
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.collabnet.svnedge.schema;

import org.apache.log4j.Logger;

import java.sql.SQLException;

public class MS021AddGroupTable implements MigrationScript {
    private Logger log = Logger.getLogger(getClass());

    private static final String CREATE_TABLE_SQL =
            "CREATE MEMORY TABLE GROUP (" +
            "ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) " + 
            "NOT NULL PRIMARY KEY," +
            "AUTHORITY BIGINT NOT NULL," +
            "NAME VARCHAR(255) NOT NULL," +
            "DESCRIPTION VARCHAR(255) NOT NULL," +
            "VERSION BIGINT NOT NULL," +
            "CONSTRAINT CTUQ_GROUP_AUTHORITY UNIQUE(AUTHORITY)," +
            "CONSTRAINT CTUQ_GROUP_NAME UNIQUE(NAME))";
    public boolean migrate(SqlUtil db) throws SQLException {
        // insert row, if it does not exist
        db.executeUpdateSql(CREATE_TABLE_SQL);
/*        db.executeUpdateSql("ALTER TABLE USER_PROPERTY ALTER COLUMN ID " +
        		    "RESTART WITH 1");*/
        return false;
    }
    
    public int[] getVersion() {
        return new int[] {3,0,1};
    }
}
